-- autogenerated lush spec on Thu 24 Apr 16:22:33 2025
-- Run :Lushify
-- then /Normal to find the Normal group and edit your fg & bg colors
local lush = require("lush")
local hsl = lush.hsl
local hsluv = lush.hsluv
local theme = lush(function(injected_functions)
  local sym = injected_functions.sym
  return {
    SpecialKey                              { fg="#585858", }, -- SpecialKey     xxx ctermfg=240 guifg=#585858
    EndOfBuffer                             { fg="#585858", }, -- EndOfBuffer    xxx ctermfg=240 guifg=#585858
    TermCursor                              { gui="reverse", }, -- TermCursor     xxx cterm=reverse gui=reverse
    NonText                                 { fg="#585858", }, -- NonText        xxx ctermfg=240 guifg=#585858
    Whitespace                              { NonText }, -- Whitespace     xxx links to NonText
    LspCodeLens                             { NonText }, -- LspCodeLens    xxx links to NonText
    LspInlayHint                            { NonText }, -- LspInlayHint   xxx links to NonText
    TelescopePreviewHyphen                  { NonText }, -- TelescopePreviewHyphen xxx links to NonText
    TelescopePromptCounter                  { NonText }, -- TelescopePromptCounter xxx links to NonText
    TelescopeResultsDiffUntracked           { NonText }, -- TelescopeResultsDiffUntracked xxx links to NonText
    FzfLuaFzfInfo                           { NonText }, -- FzfLuaFzfInfo  xxx links to NonText
    Directory                               { gui="bold", fg="#5fafff", }, -- Directory      xxx cterm=bold ctermfg=75 gui=bold guifg=#5fafff
    TelescopePreviewDirectory               { Directory }, -- TelescopePreviewDirectory xxx links to Directory
    TelescopePreviewDate                    { Directory }, -- TelescopePreviewDate xxx links to Directory
    FzfLuaDirIcon                           { Directory }, -- FzfLuaDirIcon  xxx links to Directory
    ErrorMsg                                { bg="#ff5f5f", fg="#ffffff", }, -- ErrorMsg       xxx ctermfg=231 ctermbg=203 guifg=#ffffff guibg=#ff5f5f
    NvimInvalidSpacing                      { ErrorMsg }, -- NvimInvalidSpacing xxx links to ErrorMsg
    IncSearch                               { bg="#5fd75f", fg="#000000", }, -- IncSearch      xxx ctermfg=16 ctermbg=77 guifg=#000000 guibg=#5fd75f
    FzfLuaSearch                            { IncSearch }, -- FzfLuaSearch   xxx links to IncSearch
    Search                                  { bg="#ffd787", fg="#000000", }, -- Search         xxx ctermfg=16 ctermbg=222 guifg=#000000 guibg=#ffd787
    Substitute                              { Search }, -- Substitute     xxx links to Search
    LspSignatureActiveParameter             { Search }, -- LspSignatureActiveParameter xxx links to Search
    TelescopePreviewMatch                   { Search }, -- TelescopePreviewMatch xxx links to Search
    CurSearch                               { bg="#5fd75f", fg="#000000", }, -- CurSearch      xxx ctermfg=16 ctermbg=77 guifg=#000000 guibg=#5fd75f
    MoreMsg                                 { fg="#5fd75f", }, -- MoreMsg        xxx ctermfg=77 guifg=#5fd75f
    ModeMsg                                 { gui="reverse", fg="#ffd787", }, -- ModeMsg        xxx cterm=reverse ctermfg=222 gui=reverse guifg=#ffd787
    LineNr                                  { fg="#585858", }, -- LineNr         xxx ctermfg=240 guifg=#585858
    LineNrAbove                             { LineNr }, -- LineNrAbove    xxx links to LineNr
    LineNrBelow                             { LineNr }, -- LineNrBelow    xxx links to LineNr
    TelescopeResultsLineNr                  { LineNr }, -- TelescopeResultsLineNr xxx links to LineNr
    CursorLineNr                            { gui="bold", fg="#ffffff", }, -- CursorLineNr   xxx cterm=bold ctermfg=231 gui=bold guifg=#ffffff
    GitGutterAddLineNr                      { CursorLineNr }, -- GitGutterAddLineNr xxx links to CursorLineNr
    GitGutterChangeLineNr                   { CursorLineNr }, -- GitGutterChangeLineNr xxx links to CursorLineNr
    GitGutterDeleteLineNr                   { CursorLineNr }, -- GitGutterDeleteLineNr xxx links to CursorLineNr
    FzfLuaCursorLineNr                      { CursorLineNr }, -- FzfLuaCursorLineNr xxx links to CursorLineNr
    Question                                { fg="#ff87ff", }, -- Question       xxx ctermfg=213 guifg=#ff87ff
    StatusLine                              { gui="bold,reverse", bg="#000000", fg="#c6c6c6", }, -- StatusLine     xxx cterm=bold,reverse ctermfg=251 ctermbg=16 gui=bold,reverse guifg=#c6c6c6 guibg=#000000
    MsgSeparator                            { StatusLine }, -- MsgSeparator   xxx links to StatusLine
    StatusLineNC                            { gui="reverse", bg="#000000", fg="#767676", }, -- StatusLineNC   xxx cterm=reverse ctermfg=243 ctermbg=16 gui=reverse guifg=#767676 guibg=#000000
    VertSplit                               { bg="#767676", fg="#767676", }, -- VertSplit      xxx ctermfg=243 ctermbg=243 guifg=#767676 guibg=#767676
    WinSeparator                            { VertSplit }, -- WinSeparator   xxx links to VertSplit
    Title                                   { gui="bold", }, -- Title          xxx cterm=bold gui=bold
    FloatTitle                              { Title }, -- FloatTitle     xxx links to Title
    FloatFooter                             { Title }, -- FloatFooter    xxx links to Title
    sym"@markup.heading"                    { Title }, -- @markup.heading xxx links to Title
    helpVim                                 { Title }, -- helpVim        xxx links to Title
    helpHeader                              { Title }, -- helpHeader     xxx links to Title
    Visual                                  { bg="#005f87", fg="#ffffff", }, -- Visual         xxx ctermfg=231 ctermbg=24 guifg=#ffffff guibg=#005f87
    LspReferenceText                        { Visual }, -- LspReferenceText xxx links to Visual
    SnippetTabstop                          { Visual }, -- SnippetTabstop xxx links to Visual
    TelescopePreviewLine                    { Visual }, -- TelescopePreviewLine xxx links to Visual
    TelescopeSelection                      { Visual }, -- TelescopeSelection xxx links to Visual
    WarningMsg                              { fg="#ff5f5f", }, -- WarningMsg     xxx ctermfg=203 guifg=#ff5f5f
    WildMenu                                { gui="bold", bg="#ffd787", fg="#000000", }, -- WildMenu       xxx cterm=bold ctermfg=16 ctermbg=222 gui=bold guifg=#000000 guibg=#ffd787
    Folded                                  { bg="#303030", fg="#767676", }, -- Folded         xxx ctermfg=243 ctermbg=236 guifg=#767676 guibg=#303030
    FoldColumn                              { fg="#585858", }, -- FoldColumn     xxx ctermfg=240 guifg=#585858
    CursorLineFold                          { FoldColumn }, -- CursorLineFold xxx links to FoldColumn
    DiffAdd                                 { bg="#875f87", fg="#c6c6c6", }, -- DiffAdd        xxx ctermfg=251 ctermbg=96 guifg=#c6c6c6 guibg=#875f87
    GitGutterAddLine                        { DiffAdd }, -- GitGutterAddLine xxx links to DiffAdd
    TelescopeResultsDiffAdd                 { DiffAdd }, -- TelescopeResultsDiffAdd xxx links to DiffAdd
    DiffChange                              { bg="#5f5f5f", fg="#c6c6c6", }, -- DiffChange     xxx ctermfg=251 ctermbg=59 guifg=#c6c6c6 guibg=#5f5f5f
    GitGutterChangeLine                     { DiffChange }, -- GitGutterChangeLine xxx links to DiffChange
    TelescopeResultsDiffChange              { DiffChange }, -- TelescopeResultsDiffChange xxx links to DiffChange
    DiffDelete                              { fg="#d78787", }, -- DiffDelete     xxx ctermfg=174 guifg=#d78787
    GitGutterDeleteLine                     { DiffDelete }, -- GitGutterDeleteLine xxx links to DiffDelete
    TelescopeResultsDiffDelete              { DiffDelete }, -- TelescopeResultsDiffDelete xxx links to DiffDelete
    DiffText                                { bg="#5f8787", fg="#afffff", }, -- DiffText       xxx ctermfg=159 ctermbg=66 guifg=#afffff guibg=#5f8787
    DiffTextAdd                             { DiffText }, -- DiffTextAdd    xxx links to DiffText
    Conceal                                 { fg="#585858", }, -- Conceal        xxx ctermfg=240 guifg=#585858
    SpellBad                                { gui="undercurl", sp="#ff5f5f", }, -- SpellBad       xxx cterm=underline ctermfg=203 gui=undercurl guisp=#ff5f5f
    SpellCap                                { gui="undercurl", sp="#5fafaf", }, -- SpellCap       xxx cterm=underline ctermfg=73 gui=undercurl guisp=#5fafaf
    SpellRare                               { gui="undercurl", sp="#ff87ff", }, -- SpellRare      xxx cterm=underline ctermfg=213 gui=undercurl guisp=#ff87ff
    SpellLocal                              { gui="undercurl", sp="#5faf5f", }, -- SpellLocal     xxx cterm=underline ctermfg=77 gui=undercurl guisp=#5faf5f
    Pmenu                                   { bg="#303030", }, -- Pmenu          xxx ctermbg=236 guibg=#303030
    NormalFloat                             { Pmenu }, -- NormalFloat    xxx links to Pmenu
    MessageWindow                           { Pmenu }, -- MessageWindow  xxx links to Pmenu
    PmenuSel                                { bg="#4e4e4e", }, -- PmenuSel       xxx ctermbg=239 guibg=#4e4e4e
    PopupSelected                           { PmenuSel }, -- PopupSelected  xxx links to PmenuSel
    PmenuMatch                              { bg="#303030", fg="#d787d7", }, -- PmenuMatch     xxx ctermfg=176 ctermbg=236 guifg=#d787d7 guibg=#303030
    PmenuMatchSel                           { bg="#4e4e4e", fg="#d787d7", }, -- PmenuMatchSel  xxx ctermfg=176 ctermbg=239 guifg=#d787d7 guibg=#4e4e4e
    PmenuKind                               { bg="#303030", fg="#ff5f5f", }, -- PmenuKind      xxx ctermfg=203 ctermbg=236 guifg=#ff5f5f guibg=#303030
    PmenuKindSel                            { bg="#4e4e4e", fg="#ff5f5f", }, -- PmenuKindSel   xxx ctermfg=203 ctermbg=239 guifg=#ff5f5f guibg=#4e4e4e
    PmenuExtra                              { bg="#303030", fg="#767676", }, -- PmenuExtra     xxx ctermfg=243 ctermbg=236 guifg=#767676 guibg=#303030
    PmenuExtraSel                           { bg="#4e4e4e", fg="#767676", }, -- PmenuExtraSel  xxx ctermfg=243 ctermbg=239 guifg=#767676 guibg=#4e4e4e
    PmenuThumb                              { bg="#c6c6c6", }, -- PmenuThumb     xxx ctermbg=251 guibg=#c6c6c6
    FzfLuaScrollFloatFull                   { PmenuThumb }, -- FzfLuaScrollFloatFull xxx links to PmenuThumb
    TabLine                                 { bg="#c6c6c6", fg="#000000", }, -- TabLine        xxx ctermfg=16 ctermbg=251 guifg=#000000 guibg=#c6c6c6
    TabLineSel                              { gui="bold", bg="#000000", fg="#ffffff", }, -- TabLineSel     xxx cterm=bold ctermfg=231 ctermbg=16 gui=bold guifg=#ffffff guibg=#000000
    TabLineFill                             { bg="#767676", }, -- TabLineFill    xxx ctermbg=243 guibg=#767676
    CursorColumn                            { bg="#262626", }, -- CursorColumn   xxx ctermbg=235 guibg=#262626
    CursorLine                              { bg="#262626", }, -- CursorLine     xxx ctermbg=235 guibg=#262626
    FzfLuaCursorLine                        { CursorLine }, -- FzfLuaCursorLine xxx links to CursorLine
    ColorColumn                             { bg="#303030", }, -- ColorColumn    xxx ctermbg=236 guibg=#303030
    QuickFixLine                            { bg="#5fafff", fg="#000000", }, -- QuickFixLine   xxx ctermfg=16 ctermbg=75 guifg=#000000 guibg=#5fafff
    WinBar                                  { gui="bold", }, -- WinBar         xxx cterm=bold gui=bold
    WinBarNC                                { WinBar }, -- WinBarNC       xxx links to WinBar
    Cursor                                  { bg="#ffffff", fg="#000000", }, -- Cursor         xxx guifg=#000000 guibg=#ffffff
    CursorIM                                { Cursor }, -- CursorIM       xxx links to Cursor
    FzfLuaCursor                            { Cursor }, -- FzfLuaCursor   xxx links to Cursor
    StatusLineTerm                          { gui="bold", bg="lightgreen", fg="black", }, -- StatusLineTerm xxx cterm=bold ctermfg=0 ctermbg=121 gui=bold guifg=Black guibg=LightGreen
    StatusLineTermNC                        { bg="lightgreen", fg="black", }, -- StatusLineTermNC xxx ctermfg=0 ctermbg=121 guifg=Black guibg=LightGreen
    RedrawDebugNormal                       { gui="reverse", }, -- RedrawDebugNormal xxx cterm=reverse gui=reverse
    Underlined                              { gui="underline", }, -- Underlined     xxx cterm=underline gui=underline
    sym"@string.special.url"                { Underlined }, -- @string.special.url xxx links to Underlined
    sym"@markup.underline"                  { Underlined }, -- @markup.underline xxx links to Underlined
    sym"@markup.link.url"                   { Underlined }, -- @markup.link.url xxx links to Underlined
    helpHyperTextJump                       { Underlined }, -- helpHyperTextJump xxx links to Underlined
    lCursor                                 { gui="reverse", bg="#000000", fg="#ff5fff", }, -- lCursor        xxx cterm=reverse gui=reverse guifg=#ff5fff guibg=#000000
    VisualNOS                               { bg="#5fafaf", fg="#000000", }, -- VisualNOS      xxx ctermfg=16 ctermbg=73 guifg=#000000 guibg=#5fafaf
    Normal                                  { bg="#000000", fg="#c6c6c6", }, -- Normal         xxx ctermfg=251 ctermbg=16 guifg=#c6c6c6 guibg=#000000
    NvimSpacing                             { Normal }, -- NvimSpacing    xxx links to Normal
    rstCodeBlock                            { Normal }, -- rstCodeBlock   xxx links to Normal
    vimGroup                                { Normal }, -- vimGroup       xxx links to Normal
    vimVar                                  { Normal }, -- vimVar         xxx links to Normal
    vimOper                                 { Normal }, -- vimOper        xxx links to Normal
    vimSep                                  { Normal }, -- vimSep         xxx links to Normal
    vimParenSep                             { Normal }, -- vimParenSep    xxx links to Normal
    vimOption                               { Normal }, -- vimOption      xxx links to Normal
    shNoQuote                               { Normal }, -- shNoQuote      xxx links to Normal
    shTestOpr                               { Normal }, -- shTestOpr      xxx links to Normal
    shOperator                              { Normal }, -- shOperator     xxx links to Normal
    shSetOption                             { Normal }, -- shSetOption    xxx links to Normal
    shOption                                { Normal }, -- shOption       xxx links to Normal
    shCommandSub                            { Normal }, -- shCommandSub   xxx links to Normal
    phpSpecialFunction                      { Normal }, -- phpSpecialFunction xxx links to Normal
    phpParent                               { Normal }, -- phpParent      xxx links to Normal
    phpComparison                           { Normal }, -- phpComparison  xxx links to Normal
    phpOperator                             { Normal }, -- phpOperator    xxx links to Normal
    csLogicSymbols                          { Normal }, -- csLogicSymbols xxx links to Normal
    csClassType                             { Normal }, -- csClassType    xxx links to Normal
    Terminal                                { Normal }, -- Terminal       xxx links to Normal
    TelescopeNormal                         { Normal }, -- TelescopeNormal xxx links to Normal
    FzfLuaNormal                            { Normal }, -- FzfLuaNormal   xxx links to Normal
    FzfLuaBorder                            { Normal }, -- FzfLuaBorder   xxx links to Normal
    WhichKeyIconGrey                        { Normal }, -- WhichKeyIconGrey xxx links to Normal
    Constant                                { fg="#ff87ff", }, -- Constant       xxx ctermfg=213 guifg=#ff87ff
    Character                               { Constant }, -- Character      xxx links to Constant
    Number                                  { Constant }, -- Number         xxx links to Constant
    Boolean                                 { Constant }, -- Boolean        xxx links to Constant
    sym"@constant"                          { Constant }, -- @constant      xxx links to Constant
    sym"@lsp.type.enumMember"               { Constant }, -- @lsp.type.enumMember xxx links to Constant
    fugitiveHash                            { Constant }, -- fugitiveHash   xxx links to Constant
    rstFieldName                            { Constant }, -- rstFieldName   xxx links to Constant
    shQuote                                 { Constant }, -- shQuote        xxx links to Constant
    TelescopePreviewGroup                   { Constant }, -- TelescopePreviewGroup xxx links to Constant
    TelescopePreviewUser                    { Constant }, -- TelescopePreviewUser xxx links to Constant
    TelescopePreviewRead                    { Constant }, -- TelescopePreviewRead xxx links to Constant
    TelescopePreviewBlock                   { Constant }, -- TelescopePreviewBlock xxx links to Constant
    TelescopePreviewCharDev                 { Constant }, -- TelescopePreviewCharDev xxx links to Constant
    TelescopePreviewPipe                    { Constant }, -- TelescopePreviewPipe xxx links to Constant
    TelescopeResultsConstant                { Constant }, -- TelescopeResultsConstant xxx links to Constant
    WhichKeyIconPurple                      { Constant }, -- WhichKeyIconPurple xxx links to Constant
    Statement                               { gui="bold", fg="#e4e4e4", }, -- Statement      xxx cterm=bold ctermfg=254 gui=bold guifg=#e4e4e4
    Conditional                             { Statement }, -- Conditional    xxx links to Statement
    Repeat                                  { Statement }, -- Repeat         xxx links to Statement
    Label                                   { Statement }, -- Label          xxx links to Statement
    Keyword                                 { Statement }, -- Keyword        xxx links to Statement
    Exception                               { Statement }, -- Exception      xxx links to Statement
    Operator                                { Statement }, -- Operator       xxx links to Statement
    fugitiveHeading                         { Statement }, -- fugitiveHeading xxx links to Statement
    fugitiveStagedHeading                   { Statement }, -- fugitiveStagedHeading xxx links to Statement
    fugitiveUnstagedHeading                 { Statement }, -- fugitiveUnstagedHeading xxx links to Statement
    fugitiveUntrackedHeading                { Statement }, -- fugitiveUntrackedHeading xxx links to Statement
    rstSectionDelimiter                     { Statement }, -- rstSectionDelimiter xxx links to Statement
    colortemplateKey                        { Statement }, -- colortemplateKey xxx links to Statement
    xmlTagName                              { Statement }, -- xmlTagName     xxx links to Statement
    javaScriptFunction                      { Statement }, -- javaScriptFunction xxx links to Statement
    javaScriptIdentifier                    { Statement }, -- javaScriptIdentifier xxx links to Statement
    sqlKeyword                              { Statement }, -- sqlKeyword     xxx links to Statement
    yamlBlockMappingKey                     { Statement }, -- yamlBlockMappingKey xxx links to Statement
    rubyMacro                               { Statement }, -- rubyMacro      xxx links to Statement
    rubyDefine                              { Statement }, -- rubyDefine     xxx links to Statement
    pythonInclude                           { Statement }, -- pythonInclude  xxx links to Statement
    phpStorageClass                         { Statement }, -- phpStorageClass xxx links to Statement
    phpStructure                            { Statement }, -- phpStructure   xxx links to Statement
    phpInclude                              { Statement }, -- phpInclude     xxx links to Statement
    phpDefine                               { Statement }, -- phpDefine      xxx links to Statement
    javaExternal                            { Statement }, -- javaExternal   xxx links to Statement
    javaType                                { Statement }, -- javaType       xxx links to Statement
    javaScopeDecl                           { Statement }, -- javaScopeDecl  xxx links to Statement
    javaClassDecl                           { Statement }, -- javaClassDecl  xxx links to Statement
    javaStorageClass                        { Statement }, -- javaStorageClass xxx links to Statement
    csStorage                               { Statement }, -- csStorage      xxx links to Statement
    csAccessModifier                        { Statement }, -- csAccessModifier xxx links to Statement
    csClass                                 { Statement }, -- csClass        xxx links to Statement
    csModifier                              { Statement }, -- csModifier     xxx links to Statement
    csAsyncModifier                         { Statement }, -- csAsyncModifier xxx links to Statement
    csType                                  { Statement }, -- csType         xxx links to Statement
    TelescopePreviewWrite                   { Statement }, -- TelescopePreviewWrite xxx links to Statement
    TelescopePreviewSocket                  { Statement }, -- TelescopePreviewSocket xxx links to Statement
    PreProc                                 { fg="#5fd7d7", }, -- PreProc        xxx ctermfg=116 guifg=#5fd7d7
    Include                                 { PreProc }, -- Include        xxx links to PreProc
    Define                                  { PreProc }, -- Define         xxx links to PreProc
    Macro                                   { PreProc }, -- Macro          xxx links to PreProc
    PreCondit                               { PreProc }, -- PreCondit      xxx links to PreProc
    sym"@keyword.directive"                 { PreProc }, -- @keyword.directive xxx links to PreProc
    fugitiveSymbolicRef                     { PreProc }, -- fugitiveSymbolicRef xxx links to PreProc
    fugitiveStagedModifier                  { PreProc }, -- fugitiveStagedModifier xxx links to PreProc
    fugitiveUnstagedModifier                { PreProc }, -- fugitiveUnstagedModifier xxx links to PreProc
    diffFile                                { PreProc }, -- diffFile       xxx links to PreProc
    rstDirective                            { PreProc }, -- rstDirective   xxx links to PreProc
    javaDocParam                            { PreProc }, -- javaDocParam   xxx links to PreProc
    Type                                    { fg="#5fd75f", }, -- Type           xxx ctermfg=77 guifg=#5fd75f
    StorageClass                            { Type }, -- StorageClass   xxx links to Type
    Structure                               { Type }, -- Structure      xxx links to Type
    Typedef                                 { Type }, -- Typedef        xxx links to Type
    sym"@type"                              { Type }, -- @type          xxx links to Type
    sym"@lsp.type.type"                     { Type }, -- @lsp.type.type xxx links to Type
    NvimNumberPrefix                        { Type }, -- NvimNumberPrefix xxx links to Type
    NvimOptionSigil                         { Type }, -- NvimOptionSigil xxx links to Type
    TelescopeMultiSelection                 { Type }, -- TelescopeMultiSelection xxx links to Type
    Special                                 { fg="#5fafaf", }, -- Special        xxx ctermfg=73 guifg=#5fafaf
    Tag                                     { Special }, -- Tag            xxx links to Special
    SpecialChar                             { Special }, -- SpecialChar    xxx links to Special
    SpecialComment                          { Special }, -- SpecialComment xxx links to Special
    Debug                                   { Special }, -- Debug          xxx links to Special
    sym"@variable.builtin"                  { Special }, -- @variable.builtin xxx links to Special
    sym"@variable.parameter.builtin"        { Special }, -- @variable.parameter.builtin xxx links to Special
    sym"@constant.builtin"                  { Special }, -- @constant.builtin xxx links to Special
    sym"@module.builtin"                    { Special }, -- @module.builtin xxx links to Special
    sym"@type.builtin"                      { Special }, -- @type.builtin  xxx links to Special
    sym"@attribute.builtin"                 { Special }, -- @attribute.builtin xxx links to Special
    sym"@function.builtin"                  { Special }, -- @function.builtin xxx links to Special
    sym"@constructor"                       { Special }, -- @constructor   xxx links to Special
    Delimiter                               { Special }, -- Delimiter      xxx links to Special
    sym"@punctuation.special"               { Special }, -- @punctuation.special xxx links to Special
    sym"@markup"                            { Special }, -- @markup        xxx links to Special
    sym"@tag.builtin"                       { Special }, -- @tag.builtin   xxx links to Special
    markdownHeadingDelimiter                { Special }, -- markdownHeadingDelimiter xxx links to Special
    rstHyperlinkReference                   { Special }, -- rstHyperlinkReference xxx links to Special
    rstDelimiter                            { Special }, -- rstDelimiter   xxx links to Special
    rstInterpretedText                      { Special }, -- rstInterpretedText xxx links to Special
    shDerefOp                               { Special }, -- shDerefOp      xxx links to Special
    phpVarSelector                          { Special }, -- phpVarSelector xxx links to Special
    phpMemberSelector                       { Special }, -- phpMemberSelector xxx links to Special
    TelescopePreviewLink                    { Special }, -- TelescopePreviewLink xxx links to Special
    TelescopeMatching                       { Special }, -- TelescopeMatching xxx links to Special
    FzfLuaFzfMatch                          { Special }, -- FzfLuaFzfMatch xxx links to Special
    FzfLuaFzfPointer                        { Special }, -- FzfLuaFzfPointer xxx links to Special
    FzfLuaFzfPrompt                         { Special }, -- FzfLuaFzfPrompt xxx links to Special
    DiagnosticError                         { fg="red", }, -- DiagnosticError xxx ctermfg=1 guifg=Red
    DiagnosticFloatingError                 { DiagnosticError }, -- DiagnosticFloatingError xxx links to DiagnosticError
    DiagnosticVirtualTextError              { DiagnosticError }, -- DiagnosticVirtualTextError xxx links to DiagnosticError
    DiagnosticVirtualLinesError             { DiagnosticError }, -- DiagnosticVirtualLinesError xxx links to DiagnosticError
    DiagnosticSignError                     { DiagnosticError }, -- DiagnosticSignError xxx links to DiagnosticError
    sym"@comment.error"                     { DiagnosticError }, -- @comment.error xxx links to DiagnosticError
    WhichKeyIconRed                         { DiagnosticError }, -- WhichKeyIconRed xxx links to DiagnosticError
    DiagnosticWarn                          { fg="orange", }, -- DiagnosticWarn xxx ctermfg=3 guifg=Orange
    DiagnosticFloatingWarn                  { DiagnosticWarn }, -- DiagnosticFloatingWarn xxx links to DiagnosticWarn
    DiagnosticVirtualTextWarn               { DiagnosticWarn }, -- DiagnosticVirtualTextWarn xxx links to DiagnosticWarn
    DiagnosticVirtualLinesWarn              { DiagnosticWarn }, -- DiagnosticVirtualLinesWarn xxx links to DiagnosticWarn
    DiagnosticSignWarn                      { DiagnosticWarn }, -- DiagnosticSignWarn xxx links to DiagnosticWarn
    sym"@comment.warning"                   { DiagnosticWarn }, -- @comment.warning xxx links to DiagnosticWarn
    WhichKeyIconOrange                      { DiagnosticWarn }, -- WhichKeyIconOrange xxx links to DiagnosticWarn
    WhichKeyIconYellow                      { DiagnosticWarn }, -- WhichKeyIconYellow xxx links to DiagnosticWarn
    DiagnosticInfo                          { fg="lightblue", }, -- DiagnosticInfo xxx ctermfg=4 guifg=LightBlue
    DiagnosticFloatingInfo                  { DiagnosticInfo }, -- DiagnosticFloatingInfo xxx links to DiagnosticInfo
    DiagnosticVirtualTextInfo               { DiagnosticInfo }, -- DiagnosticVirtualTextInfo xxx links to DiagnosticInfo
    DiagnosticVirtualLinesInfo              { DiagnosticInfo }, -- DiagnosticVirtualLinesInfo xxx links to DiagnosticInfo
    DiagnosticSignInfo                      { DiagnosticInfo }, -- DiagnosticSignInfo xxx links to DiagnosticInfo
    sym"@comment.note"                      { DiagnosticInfo }, -- @comment.note  xxx links to DiagnosticInfo
    WhichKeyIconBlue                        { DiagnosticInfo }, -- WhichKeyIconBlue xxx links to DiagnosticInfo
    DiagnosticHint                          { fg="lightgrey", }, -- DiagnosticHint xxx ctermfg=7 guifg=LightGrey
    DiagnosticFloatingHint                  { DiagnosticHint }, -- DiagnosticFloatingHint xxx links to DiagnosticHint
    DiagnosticVirtualTextHint               { DiagnosticHint }, -- DiagnosticVirtualTextHint xxx links to DiagnosticHint
    DiagnosticVirtualLinesHint              { DiagnosticHint }, -- DiagnosticVirtualLinesHint xxx links to DiagnosticHint
    DiagnosticSignHint                      { DiagnosticHint }, -- DiagnosticSignHint xxx links to DiagnosticHint
    WhichKeyIconCyan                        { DiagnosticHint }, -- WhichKeyIconCyan xxx links to DiagnosticHint
    DiagnosticOk                            { fg="lightgreen", }, -- DiagnosticOk   xxx ctermfg=10 guifg=LightGreen
    DiagnosticFloatingOk                    { DiagnosticOk }, -- DiagnosticFloatingOk xxx links to DiagnosticOk
    DiagnosticVirtualTextOk                 { DiagnosticOk }, -- DiagnosticVirtualTextOk xxx links to DiagnosticOk
    DiagnosticVirtualLinesOk                { DiagnosticOk }, -- DiagnosticVirtualLinesOk xxx links to DiagnosticOk
    DiagnosticSignOk                        { DiagnosticOk }, -- DiagnosticSignOk xxx links to DiagnosticOk
    WhichKeyIconGreen                       { DiagnosticOk }, -- WhichKeyIconGreen xxx links to DiagnosticOk
    Comment                                 { fg="#5fafff", }, -- Comment        xxx ctermfg=75 guifg=#5fafff
    DiagnosticUnnecessary                   { Comment }, -- DiagnosticUnnecessary xxx links to Comment
    sym"@comment"                           { Comment }, -- @comment       xxx links to Comment
    sym"@lsp.type.comment"                  { Comment }, -- @lsp.type.comment xxx links to Comment
    sym"@markup.raw"                        { Comment }, -- @markup.raw    xxx links to Comment
    vimCommentString                        { Comment }, -- vimCommentString xxx links to Comment
    TelescopeResultsComment                 { Comment }, -- TelescopeResultsComment xxx links to Comment
    FzfLuaDirPart                           { Comment }, -- FzfLuaDirPart  xxx links to Comment
    WhichKeySeparator                       { Comment }, -- WhichKeySeparator xxx links to Comment
    WhichKeyValue                           { Comment }, -- WhichKeyValue  xxx links to Comment
    String                                  { fg="#ffd787", }, -- String         xxx ctermfg=222 guifg=#ffd787
    sym"@string"                            { String }, -- @string        xxx links to String
    NvimString                              { String }, -- NvimString     xxx links to String
    markdownUrl                             { String }, -- markdownUrl    xxx links to String
    TelescopePreviewSize                    { String }, -- TelescopePreviewSize xxx links to String
    TelescopePreviewExecute                 { String }, -- TelescopePreviewExecute xxx links to String
    Todo                                    { gui="reverse", bg="#000000", fg="#5fd7d7", }, -- Todo           xxx cterm=reverse ctermfg=116 ctermbg=16 gui=reverse guifg=#5fd7d7 guibg=#000000
    sym"@comment.todo"                      { Todo }, -- @comment.todo  xxx links to Todo
    PopupNotification                       { Todo }, -- PopupNotification xxx links to Todo
    sym"@markup.strong"                     { gui="bold", }, -- @markup.strong xxx cterm=bold gui=bold
    sym"@markup.italic"                     { gui="italic", }, -- @markup.italic xxx cterm=italic gui=italic
    sym"@markup.strikethrough"              { gui="strikethrough", }, -- @markup.strikethrough xxx cterm=strikethrough gui=strikethrough
    Added                                   { fg="#5fd75f", }, -- Added          xxx ctermfg=77 guifg=#5fd75f
    sym"@diff.plus"                         { Added }, -- @diff.plus     xxx links to Added
    Removed                                 { fg="#d78787", }, -- Removed        xxx ctermfg=174 guifg=#d78787
    sym"@diff.minus"                        { Removed }, -- @diff.minus    xxx links to Removed
    Changed                                 { fg="#5fafff", }, -- Changed        xxx ctermfg=75 guifg=#5fafff
    sym"@diff.delta"                        { Changed }, -- @diff.delta    xxx links to Changed
    sym"@markup.heading.1.delimiter.vimdoc" { gui="underdouble,nocombine", bg="bg", fg="bg", sp="fg", }, -- @markup.heading.1.delimiter.vimdoc xxx cterm=underdouble,nocombine gui=underdouble,nocombine guifg=bg guibg=bg guisp=fg
    sym"@markup.heading.2.delimiter.vimdoc" { gui="underline,nocombine", bg="bg", fg="bg", sp="fg", }, -- @markup.heading.2.delimiter.vimdoc xxx cterm=underline,nocombine gui=underline,nocombine guifg=bg guibg=bg guisp=fg
    DiagnosticDeprecated                    { gui="strikethrough", sp="red", }, -- DiagnosticDeprecated xxx cterm=strikethrough gui=strikethrough guisp=Red
    sym"@lsp.mod.deprecated"                { DiagnosticDeprecated }, -- @lsp.mod.deprecated xxx links to DiagnosticDeprecated
    FloatShadow                             { bg="black", blend=80, }, -- FloatShadow    xxx guibg=Black blend=80
    FloatShadowThrough                      { bg="black", blend=100, }, -- FloatShadowThrough xxx guibg=Black blend=100
    MatchParen                              { gui="bold", fg="#ff00af", }, -- MatchParen     xxx cterm=bold ctermfg=199 gui=bold guifg=#ff00af
    RedrawDebugClear                        { bg="yellow", }, -- RedrawDebugClear xxx ctermbg=11 guibg=Yellow
    RedrawDebugComposed                     { bg="green", }, -- RedrawDebugComposed xxx ctermbg=10 guibg=Green
    RedrawDebugRecompose                    { bg="red", }, -- RedrawDebugRecompose xxx ctermbg=9 guibg=Red
    Error                                   { bg="#ff5f5f", fg="#ffffff", }, -- Error          xxx ctermfg=231 ctermbg=203 guifg=#ffffff guibg=#ff5f5f
    NvimInvalid                             { Error }, -- NvimInvalid    xxx links to Error
    DiagnosticUnderlineError                { gui="underline", sp="red", }, -- DiagnosticUnderlineError xxx cterm=underline gui=underline guisp=Red
    DiagnosticUnderlineWarn                 { gui="underline", sp="orange", }, -- DiagnosticUnderlineWarn xxx cterm=underline gui=underline guisp=Orange
    DiagnosticUnderlineInfo                 { gui="underline", sp="lightblue", }, -- DiagnosticUnderlineInfo xxx cterm=underline gui=underline guisp=LightBlue
    DiagnosticUnderlineHint                 { gui="underline", sp="lightgrey", }, -- DiagnosticUnderlineHint xxx cterm=underline gui=underline guisp=LightGrey
    DiagnosticUnderlineOk                   { gui="underline", sp="lightgreen", }, -- DiagnosticUnderlineOk xxx cterm=underline gui=underline guisp=LightGreen
    NvimInternalError                       { bg="red", fg="red", }, -- NvimInternalError xxx ctermfg=9 ctermbg=9 guifg=Red guibg=Red
    NvimFigureBrace                         { NvimInternalError }, -- NvimFigureBrace xxx links to NvimInternalError
    NvimSingleQuotedUnknownEscape           { NvimInternalError }, -- NvimSingleQuotedUnknownEscape xxx links to NvimInternalError
    NvimInvalidSingleQuotedUnknownEscape    { NvimInternalError }, -- NvimInvalidSingleQuotedUnknownEscape xxx links to NvimInternalError
    ToolbarButton                           { bg="#ffffff", fg="#000000", }, -- ToolbarButton  xxx ctermfg=16 ctermbg=231 guifg=#000000 guibg=#ffffff
    debugPC                                 { gui="reverse", fg="#5f87af", }, -- debugPC        xxx cterm=reverse ctermfg=67 gui=reverse guifg=#5f87af
    debugBreakpoint                         { gui="reverse", fg="#5fafaf", }, -- debugBreakpoint xxx cterm=reverse ctermfg=73 gui=reverse guifg=#5fafaf
    diffSubname                             { fg="#ff87ff", }, -- diffSubname    xxx ctermfg=213 guifg=#ff87ff
    dirType                                 { fg="#d787d7", }, -- dirType        xxx ctermfg=176 guifg=#d787d7
    dirPermissionUser                       { fg="#5faf5f", }, -- dirPermissionUser xxx ctermfg=71 guifg=#5faf5f
    dirPermissionGroup                      { fg="#af875f", }, -- dirPermissionGroup xxx ctermfg=137 guifg=#af875f
    dirPermissionOther                      { fg="#5fafaf", }, -- dirPermissionOther xxx ctermfg=73 guifg=#5fafaf
    dirOwner                                { fg="#767676", }, -- dirOwner       xxx ctermfg=243 guifg=#767676
    dirGroup                                { fg="#767676", }, -- dirGroup       xxx ctermfg=243 guifg=#767676
    dirTime                                 { fg="#767676", }, -- dirTime        xxx ctermfg=243 guifg=#767676
    dirSize                                 { fg="#ffd787", }, -- dirSize        xxx ctermfg=222 guifg=#ffd787
    dirSizeMod                              { fg="#d787d7", }, -- dirSizeMod     xxx ctermfg=176 guifg=#d787d7
    FilterMenuDirectorySubtle               { fg="#878787", }, -- FilterMenuDirectorySubtle xxx ctermfg=102 guifg=#878787
    dirFilterMenuBookmarkPath               { fg="#878787", }, -- dirFilterMenuBookmarkPath xxx ctermfg=102 guifg=#878787
    dirFilterMenuHistoryPath                { fg="#878787", }, -- dirFilterMenuHistoryPath xxx ctermfg=102 guifg=#878787
    FilterMenuLineNr                        { fg="#878787", }, -- FilterMenuLineNr xxx ctermfg=102 guifg=#878787
    CocSearch                               { fg="#ffd787", }, -- CocSearch      xxx ctermfg=222 guifg=#ffd787
    GitGutterAddInvisible                   { fg="bg", }, -- GitGutterAddInvisible xxx guifg=bg
    GitGutterChangeInvisible                { fg="bg", }, -- GitGutterChangeInvisible xxx guifg=bg
    GitGutterChangeDeleteInvisible          { GitGutterChangeInvisible }, -- GitGutterChangeDeleteInvisible xxx links to GitGutterChangeInvisible
    GitGutterDeleteInvisible                { fg="bg", }, -- GitGutterDeleteInvisible xxx guifg=bg
    GitGutterAdd                            { fg="#c6c6c6", }, -- GitGutterAdd   xxx ctermfg=251 guifg=#c6c6c6
    GitGutterChange                         { fg="#c6c6c6", }, -- GitGutterChange xxx ctermfg=251 guifg=#c6c6c6
    GitGutterChangeDelete                   { GitGutterChange }, -- GitGutterChangeDelete xxx links to GitGutterChange
    GitGutterDelete                         { fg="#d78787", }, -- GitGutterDelete xxx ctermfg=174 guifg=#d78787
    GitGutterAddIntraLine                   { gui="reverse", }, -- GitGutterAddIntraLine xxx cterm=reverse gui=reverse
    GitGutterDeleteIntraLine                { gui="reverse", }, -- GitGutterDeleteIntraLine xxx cterm=reverse gui=reverse
    diffAdded                               { fg="#c6c6c6", }, -- diffAdded      xxx ctermfg=251 guifg=#c6c6c6
    diffChanged                             { fg="#c6c6c6", }, -- diffChanged    xxx ctermfg=251 guifg=#c6c6c6
    diffRemoved                             { fg="#d78787", }, -- diffRemoved    xxx ctermfg=174 guifg=#d78787
    FzfLuaBackdrop                          { bg="black", }, -- FzfLuaBackdrop xxx guibg=Black
    FzfLuaHeaderBind                        { fg="blanchedalmond", }, -- FzfLuaHeaderBind xxx guifg=BlanchedAlmond
    FzfLuaHeaderText                        { fg="brown1", }, -- FzfLuaHeaderText xxx guifg=Brown1
    FzfLuaPathColNr                         { fg="cadetblue1", }, -- FzfLuaPathColNr xxx guifg=CadetBlue1
    FzfLuaPathLineNr                        { fg="lightgreen", }, -- FzfLuaPathLineNr xxx guifg=LightGreen
    FzfLuaLiveSym                           { fg="brown1", }, -- FzfLuaLiveSym  xxx guifg=Brown1
    FzfLuaBufName                           { fg="lightmagenta", }, -- FzfLuaBufName  xxx guifg=LightMagenta
    FzfLuaBufNr                             { fg="blanchedalmond", }, -- FzfLuaBufNr    xxx guifg=BlanchedAlmond
    FzfLuaBufFlagCur                        { fg="brown1", }, -- FzfLuaBufFlagCur xxx guifg=Brown1
    FzfLuaBufFlagAlt                        { fg="cadetblue1", }, -- FzfLuaBufFlagAlt xxx guifg=CadetBlue1
    FzfLuaTabTitle                          { gui="bold", fg="lightskyblue1", }, -- FzfLuaTabTitle xxx cterm=bold gui=bold guifg=LightSkyBlue1
    FzfLuaTabMarker                         { gui="bold", fg="blanchedalmond", }, -- FzfLuaTabMarker xxx cterm=bold gui=bold guifg=BlanchedAlmond
  }
end)
return theme
